# Generated by Django 3.2.8 on 2021-10-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrid', '0004_footballer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
